### ISSUE TITLE
请问是通过什么样的手段来了解天翼客户端拨号机制的

### ISSUE THREAD

**Issue by MONOY** [GDCTSCP/GDCTSCP#6]
我最近也在着手破我们学校的天翼校园客户端，能否介绍一下你的经验我来参考。

**Comment by mynuolr** [comment]
嗯，逆向出来的，如果你是广东校园天翼，使用portal的认证方式，那么这个脚本理论改nasip为你学校的也可以使用的。我没试过

**Comment by MONOY** [comment]
请问是用什么工具逆向？能简单介绍一下吗？谢谢

**Comment by mynuolr** [comment]
逆向APK
